In [43]:
#algoritmo de dijkstra
import numpy as np

#inicializando o grafo

numeroVertices = int(input("Digite o número de vértices: "))
print("Grafo criado. Agora adicione arestas ao grafo.")
                     
vertices = np.zeros((numeroVertices,2), dtype=np.int64, order='C')
arestas = np.zeros((numeroVertices,numeroVertices,2), dtype=np.int64, order='F')

#adiciona uma aresta ao grafo. não adiciona vértice
def adicionar(vertice1, vertice2, custo):
    if vertice1 == vertice2 or (vertice1 and vertice2) >=5:
        return "Não foi possível adicionar uma aresta."
    
    elif arestas[vertice1-1][vertice2-1][0]==1:
        return "Já existe uma aresta"
        
    else:
        arestas[vertice1-1][vertice2-1][0][0]=1
        arestas[vertice1-1][vertice2-1][0][1]=custo
        return "Aresta adicionada"

#modifica apenas o custo da aresta
def modificar(vertice1, vertice2, custo):
    if vertice1 == vertice2 or (vertice1 and vertice2) >=5:
        return "Não existe uma aresta para este vértice"
    
    else:
        arestas[vertice1-1][vertice2-1][1]=custo
        return "Custo da aresta modificado"
        
#remove uma aresta do grafo. não adiciona vértice
def remover(vertice1, vertice2):
    if vertice1 == vertice2 or (vertice1 and vertice2) >=5:
        return "Não foi possível remover uma aresta para o próprio vértice."
    
    else:
        arestas[vertice1-1][vertice2-1][0]=0
        arestas[vertice1-1][vertice2-1][1]=0
        return "Aresta removida."
    
def verificar(vertice1,vertice2):
    if arestas[vertice1-1][vertice2-1][0]==1:
        return "Já existe uma aresta"
    
def calcularDistancia(inicio,fim):
    verticeAtual = None
    vertice[inicio][0]=0
    vertice[inicio][1]=-1
    
    for i in arestas:
        if aresta[inicio][i][0]==1:
            #pegar o valor do custo e atualizar a tabela de vertice

Digite o número de vértices: 5
Grafo criado. Agora adicione arestas ao grafo.


In [39]:
teste = 10
arestas[0][0][1]=teste
print(arestas)

[[[ 0 10]
  [ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]]]


In [44]:
#configuração da busca e adição das arestas
inicio = int(input("digite o vértice inicial: "))
vertices[inicio-1][0]=0
vertices[inicio-1][1]=-1

print("Adicionar arestas >>>")

while(True):
    vertice1=int(input("Digite o primeiro vértice(-1 para sair): "))
    if vertice1==-1:
        break
    vertice2=int(input("Digite o segundo vértice: "))
    custo=int(input("Digite o custo da aresta: "))
    if vertice1 == vertice2:
        print("Não foi possível adicionar uma aresta para o próprio vértice.")
    
    elif arestas[vertice1-1][vertice2-1][0]==1:
        print("Já existe uma aresta")
        
    else:
        arestas[vertice1-1][vertice2-1][0]=1
        arestas[vertice1-1][vertice2-1][1]=custo
        print("Aresta adicionada")

digite o vértice inicial: 1
Adicionar arestas >>>
Digite o primeiro vértice(-1 para sair): 1
Digite o segundo vértice: 2
Digite o custo da aresta: 5
Aresta adicionada
Digite o primeiro vértice(-1 para sair): 1
Digite o segundo vértice: 3
Digite o custo da aresta: 4
Aresta adicionada
Digite o primeiro vértice(-1 para sair): 5
Digite o segundo vértice: 2
Digite o custo da aresta: 5
Aresta adicionada
Digite o primeiro vértice(-1 para sair): 1
Digite o segundo vértice: 4
Digite o custo da aresta: 10
Aresta adicionada
Digite o primeiro vértice(-1 para sair): 2
Digite o segundo vértice: 3
Digite o custo da aresta: 34
Aresta adicionada
Digite o primeiro vértice(-1 para sair): -1


In [45]:
arestas

array([[[ 0,  0],
        [ 1,  5],
        [ 1,  4],
        [ 1, 10],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 1, 34],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 1,  5],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]]], dtype=int64)